tinyMCE.addI18n("en.placesurf_dlg",{
title:"Insert PlaceSurf Google Earth link",
button_description:"PlaceSurf.com - Insert Google Earth link on selected text",
latitude:"Latitude",
longitude:"Longitude",
placename:"Placename (heading)",
description:"Description",
briefdescription:"Brief Description (optional)",
testlink:"Test link",
location_attributes:"Location Attributes",
searchmap:"Search map",
searchmapclear:"Clear",
mapinstructions:"Scroll mouse wheel to zoom - Click on map to select latitude/longitude values.<br>Try selecting different map types (Map/Sat/Hybrid/Terrain) to highlight geographical features.",
char_remaining:"Characters remaining",
max_char:"Characters remaining",
clearfields:"Clear",
gotoplacesurf:"Goto <a href='http://placesurf.com/'>placesurf.com</a>",
instructions1:"Select your lat/long location using the map on the right<br />(or type the lat/long yourself in the fields below).",
instructions2:"Enter the details below for your selected location - placename and description(optional).",
instructions3:"Click the \"Test link\" button to test your new link.",
instructions4:"Finally click the insert link to add it to your post for the selected text.",
instructions5:"For best results make sure your browser is <a href='http://placesurf.com/singleclick.php' class=psa  target=_blank >setup correctly</a> for Google Earth single-click (recommended).",
});


